from enum import Enum

class LiquidityEventType(Enum):
    EQUAL_HIGH = "EQUAL_HIGH"
    EQUAL_LOW = "EQUAL_LOW"
    LIQUIDITY_POOL = "LIQUIDITY_POOL"
    LIQUIDITY_SWEEP = "LIQUIDITY_SWEEP"
    LIQUIDITY_GRAB = "LIQUIDITY_GRAB"
    INTERNAL_LIQUIDITY = "INTERNAL_LIQUIDITY"
    EXTERNAL_LIQUIDITY = "EXTERNAL_LIQUIDITY"
    MITIGATION = "MITIGATION"
    INDUCEMENT = "INDUCEMENT"
    LIQUIDITY_VOID = "LIQUIDITY_VOID"
