from enum import Enum

class MarketRegimeEnum(Enum):
    STRONG_UPTREND = "STRONG_UPTREND"
    WEAK_UPTREND = "WEAK_UPTREND"
    STRONG_DOWNTREND = "STRONG_DOWNTREND"
    WEAK_DOWNTREND = "WEAK_DOWNTREND"
    CONSOLIDATION = "CONSOLIDATION"
    COMPRESSION = "COMPRESSION"
    EXPANSION = "EXPANSION"
    ACCUMULATION = "ACCUMULATION"
    DISTRIBUTION = "DISTRIBUTION"
    REVERSAL_TRANSITION = "REVERSAL_TRANSITION"
    UNKNOWN = "UNKNOWN"
