# Market Regime Definitions

TREND = "TREND"
RANGE = "RANGE"
ACCUMULATION = "ACCUMULATION"
DISTRIBUTION = "DISTRIBUTION"
EXPANSION = "EXPANSION"
COMPRESSION = "COMPRESSION"
REVERSAL = "REVERSAL"
UNKNOWN = "UNKNOWN"

SUPPORTED_MARKET_REGIMES = {
    "TREND": TREND,
    "RANGE": RANGE,
    "ACCUMULATION": ACCUMULATION,
    "DISTRIBUTION": DISTRIBUTION,
    "EXPANSION": EXPANSION,
    "COMPRESSION": COMPRESSION,
    "REVERSAL": REVERSAL,
    "UNKNOWN": UNKNOWN,
}
