ASIA = "ASIA"
LONDON = "LONDON"
NEW_YORK = "NEW_YORK"
OVERLAP = "OVERLAP"
SYDNEY = "SYDNEY"
TOKYO = "TOKYO"
CLOSED = "CLOSED"

SUPPORTED_SESSIONS = {
    "ASIA": ASIA,
    "LONDON": LONDON,
    "NEW_YORK": NEW_YORK,
    "OVERLAP": OVERLAP,
    "SYDNEY": SYDNEY,
    "TOKYO": TOKYO,
}
