SCALPING = "SCALPING"
INTRADAY = "INTRADAY"
SWING = "SWING"
POSITION = "POSITION"

SUPPORTED_STRATEGIES = {
    "SCALPING": SCALPING,
    "INTRADAY": INTRADAY,
    "SWING": SWING,
    "POSITION": POSITION,
}
